-- 20260717000001_harden_otp_and_add_cantonese.sql
--
-- Closes OTP replay/race windows and adds first-class Cantonese translations.
-- Bridges existing databases with the atomic OTP service and yue-enabled UI.
-- Exists so fresh and upgraded Filterest instances enforce the same contract.
-- VERSION_DB: 8.0.50

ALTER TABLE IF EXISTS public.system_lang_keys
    ADD COLUMN IF NOT EXISTS yue text;

ALTER TABLE IF EXISTS public.system_lang_keys_archive
    ADD COLUMN IF NOT EXISTS yue text;

-- Keep only the newest challenge before making user+purpose a single-row
-- state machine. This makes the migration safe for databases that already
-- contain rows created by concurrent legacy requests.
WITH ranked_challenges AS (
    SELECT id,
           row_number() OVER (
               PARTITION BY user_id, lower(btrim(purpose))
               ORDER BY created_at DESC NULLS LAST, id DESC
           ) AS duplicate_rank
    FROM restricted.verification_codes
)
DELETE FROM restricted.verification_codes AS challenge
USING ranked_challenges AS ranked
WHERE challenge.id = ranked.id
  AND ranked.duplicate_rank > 1;

UPDATE restricted.verification_codes
SET purpose = lower(btrim(purpose)),
    target_email = lower(btrim(target_email)),
    attempts = COALESCE(attempts, 0),
    max_attempts = COALESCE(max_attempts, 5),
    created_at = COALESCE(created_at, NOW());

ALTER TABLE restricted.verification_codes
    ALTER COLUMN attempts SET DEFAULT 0,
    ALTER COLUMN attempts SET NOT NULL,
    ALTER COLUMN max_attempts SET DEFAULT 5,
    ALTER COLUMN max_attempts SET NOT NULL,
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN created_at SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'verification_codes_attempts_nonnegative'
          AND conrelid = 'restricted.verification_codes'::regclass
    ) THEN
        ALTER TABLE restricted.verification_codes
            ADD CONSTRAINT verification_codes_attempts_nonnegative
            CHECK (attempts >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'verification_codes_max_attempts_positive'
          AND conrelid = 'restricted.verification_codes'::regclass
    ) THEN
        ALTER TABLE restricted.verification_codes
            ADD CONSTRAINT verification_codes_max_attempts_positive
            CHECK (max_attempts > 0);
    END IF;
END $$;

DROP INDEX IF EXISTS restricted.idx_verification_codes_user_purpose;
CREATE UNIQUE INDEX IF NOT EXISTS uq_verification_codes_user_purpose
    ON restricted.verification_codes (user_id, purpose);

CREATE TABLE IF NOT EXISTS restricted.otp_send_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    purpose character varying(50) NOT NULL,
    requested_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_otp_send_events_user_purpose_requested
    ON restricted.otp_send_events (user_id, purpose, requested_at);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'otp_send_events_user_id_fkey'
          AND conrelid = 'restricted.otp_send_events'::regclass
    ) THEN
        ALTER TABLE restricted.otp_send_events
            ADD CONSTRAINT otp_send_events_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES public.system_users(id)
            ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('public.system_db_version') IS NOT NULL THEN
        INSERT INTO public.system_db_version (version, description)
        SELECT '8.0.50', 'Added atomic single-challenge OTP storage, persistent send throttling, and Cantonese language columns.'
        WHERE NOT EXISTS (
            SELECT 1 FROM public.system_db_version WHERE version = '8.0.50'
        );
    END IF;
END $$;
